--11
CREATE TABLE STRANGER_STRINGS.Rol_X_Usuario(
Id_Rol INT IDENTITY(1,1),
Id_Usuario INT IDENTITY(1,1),
PRIMARY KEY (Id_Rol, Id_Usuario),
FOREIGN KEY (Id_Rol) REFERENCES STRANGER_STRINGS.Rol (Id_Rol),
FOREIGN KEY (Id_Usuario) REFERENCES STRANGER_STRINGS.Usuario (Id_Usuario))