--11
CREATE TABLE STRANGER_STRINGS.Rol_X_Usuario(
Id_Rol INT IDENTITY(1,1),
Id_Usuario INT IDENTITY(1,1),
CONSTRAINT PK_Id_Rol_X_Usuario PRIMARY KEY (Id_Rol, Id_Usuario),
CONSTRAINT FK_Rol FOREIGN KEY (Id_Rol) REFERENCES STRANGER_STRINGS.Rol (Id_Rol),
CONSTRAINT FK_Usuario FOREIGN KEY (Id_Usuario) REFERENCES STRANGER_STRINGS.Usuario (Id_Usuario))